language: node_js
node_js:
  - "14"
before_script:
  - cd 05-IONIC-CLI-SLIDE
  - npm install
script: npm run build
deploy:
  local-dir: 05-IONIC-CLI-SLIDE/www
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: main
notifications:
  email: false